version: "3.8"
volumes:
    db-store:
services:
    db:
        build: ./docker/mysql
        volumes:
            - db-store:/var/lib/mysql
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: testdb
            MYSQL_USER: testuser
            MYSQL_PASSWORD: testpassword
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            TZ: Asia/Tokyo
        cap_add:
            - SYS_NICE
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10